# 1. Bibliotecas e configurações

In [1]:
from pathlib import Path
import sys

ROOT = Path.cwd().parent
sys.path.append(str(ROOT))

In [2]:
from src.collect.geoinfo import coletar_geoinfo
from src.utils.preprocessing import corrigir_instituicoes_manuais, similaridade_titulos, limpar_artigos
import pandas as pd

In [3]:
BASE_DIR = Path("..")

DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

RAW_DIR.mkdir(parents=True, exist_ok=True)

ARQUIVO_SAIDA = RAW_DIR / "geoinfo_artigos_raw.csv"
ARQUIVO_PROCESSADO = PROCESSED_DIR / "geoinfo_artigos_processed.csv"

# 2. Coletar Artigos do GEOINFO

In [4]:
df = coletar_geoinfo()

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Iniciando a coleta de dados
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Extraindo edições do GEOINFO...
Servidor obtido da URL final (http://mtc-m16d.sid.inpe.br/col/sid.inpe.br/mtc-m19/2014/06.02.15.03/doc/default.html): mtc-m16d
Frame 'body' não encontrado.

Edições encontradas: 25

Total de edições: 25

------------------------------------------------------------
Edição 1/25
25a. Edição São José dos Campos 2025
------------------------------------------------------------

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Processando edição: 25a. Edição São José dos Campos 2025
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[DEBUG] Edição recebida: '25a. Edição São José dos Campos 2025'
[DEBUG] URL edição: http://urlib.net/ibi/8JMKD2USPTW34P/4DKC4FB
Servidor obtido da URL final (http://mtc-m16c.sid.inpe.br/ibi/8JMKD2USPTW34P/4DKC4FB): mtc-m16c
Frame body encontrado:
http://mtc-m16c.sid.inpe.br/displaydoccontent.cgi/sid.inpe.br/mtc-m16c/2025/06.05.18.15?nonemptyquerystring=couldBeAnyValue
Servidor final: mtc-m16c
Artigos encontrados: 40
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.04/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[1/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.04/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.04/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.14.04.41?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 1
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.46/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[2/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.46/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.46/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.14.46.57?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 2
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.12/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[3/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.12/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.12/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.17.12.02?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 3
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.34/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[4/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.34/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.34/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.14.34.52?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 4
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.52/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[5/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.52/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.52/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.14.52.06?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 5
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.22/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[6/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.22/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.22/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.13.22.06?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 6
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.12/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[7/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.12/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.12/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.12.12.41?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 7
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/05.29.18.05/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[8/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/05.29.18.05/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/05.29.18.05/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/05.29.18.05.45?ibiurl.backgroundlanguage=en
Campos encontrados: 38

Artigos coletados na edição: 8
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.49/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[9/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.49/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.49/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.13.49.51?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 9
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.03.18.22/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[10/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.03.18.22/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.03.18.22/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.03.18.22.09?ibiurl.backgroundlanguage=en
Campos encontrados: 38

Artigos coletados na edição: 10
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.03.18.35/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[11/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.03.18.35/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.03.18.35/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.03.18.35.40?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 11
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.38/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[12/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.38/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.38/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.14.38.28?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 12
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.56/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[13/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.56/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.56/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.12.56.18?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 13
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.12.57/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[14/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.12.57/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.12.57/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.04.12.57.50?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 14
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.02/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[15/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.02/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.02/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.17.02.40?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 15
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.06/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[16/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.06/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.17.06/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.17.06.03?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 16
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.09/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[17/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.09/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.09/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.14.09.38?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 17
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.09/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[18/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.09/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.09/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.04.14.09.12?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 18
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.18/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[19/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.18/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.18/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.04.14.18.09?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 19
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.12.37/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[20/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.12.37/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.12.37/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.04.12.37.44?ibiurl.backgroundlanguage=en
Campos encontrados: 39

Artigos coletados na edição: 20
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.53/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[21/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.53/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.53/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.13.53.56?ibiurl.backgroundlanguage=en
Campos encontrados: 38

Artigos coletados na edição: 21
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.42/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[22/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.42/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.14.42/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.04.14.42.54?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 22
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.00/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[23/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.00/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.14.00/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.14.00.05?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 23
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.17.59/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[24/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.17.59/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.17.59/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.04.17.59.43?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 24
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.39/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[25/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.39/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.13.39/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.13.39.32?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 25
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.13.17/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[26/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.13.17/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.04.13.17/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.04.13.17.01?ibiurl.backgroundlanguage=en
Campos encontrados: 40

Artigos coletados na edição: 26
[DEBUG] Hosts candidatos: ['mtc-m16c.sid.inpe.br']
[DEBUG] Testando host 'mtc-m16c.sid.inpe.br':
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.24/doc/thisInformationItemHomePage.html
[OK] Host funcionou: mtc-m16c.sid.inpe.br

[27/40]
URL artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.24/doc/thisInformationItemHomePage.html

Acessando artigo:
http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mtc-m16c/2025/06.05.12.24/doc/thisInformationItemHomePage.html
Frame header encontrado.
Acessando metadata:
http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m16c/2025/06.05.12.24.36?ibiurl.backgroundlanguage=en
Campos encontrados: 39


## 2.1. Validação dos Artigos Coletados

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titulo         683 non-null    str
 1   ano            683 non-null    str
 2   autores        683 non-null    str
 3   instituicoes   678 non-null    str
 4   edicao         683 non-null    str
 5   identificador  683 non-null    str
 6   language       682 non-null    str
 7   url_edicao     683 non-null    str
 8   url_artigo     683 non-null    str
 9   url_metadata   683 non-null    str
dtypes: str(10)
memory usage: 53.5 KB

In [6]:
df.head(3)

,titulo,ano,autores,instituicoes,edicao,identificador,language,url_edicao,url_artigo,url_metadata
0,Reproducible and empirical method refines Frac...,2025,"1 Adorno, Bruno Vargas 2 Nesbitt, Lorien 3 Ama...",1 National Institute for Space Research (INPE)...,25a. Edição São José dos Campos 2025,8JMKD2USPTW34P/4DKBAQH,en,http://urlib.net/ibi/8JMKD2USPTW34P/4DKC4FB,http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mt...,http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m1...
1,Potential Effects of Legal Reserve Exclusion o...,2025,"1 Andrade, Pedro Ribeiro 2 Rodrigues, Erick Te...",1 National Institute for Space Research (INPE)...,25a. Edição São José dos Campos 2025,8JMKD2USPTW34P/4DKBE9S,en,http://urlib.net/ibi/8JMKD2USPTW34P/4DKC4FB,http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mt...,http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m1...
2,Bill 191/2020: Illegal Mining and Land Use Lan...,2025,"1 Chuizaca-Espinoza, Isabel Adriana 2 Amaral, ...",1 National Institute for Space Research (INPE)...,25a. Edição São José dos Campos 2025,8JMKD2USPTW34P/4DKBSAB,en,http://urlib.net/ibi/8JMKD2USPTW34P/4DKC4FB,http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/mt...,http://mtc-m16c.sid.inpe.br/sid.inpe.br/mtc-m1...

In [7]:
df["edicao"].value_counts()

edicao
24a. Edição São José dos Campos 2023    61
23a. Edição On-Line 2022                48
20a. Edição São José dos Campos 2019    43
25a. Edição São José dos Campos 2025    40
18a. Edição Salvador 2017               37
21a. Edição On-Line 2020                36
6a. Edição Campos do Jordão 2004        35
22a. Edição On-Line 2021                29
9a. Edição Campos do Jordão 2007        29
7a. Edição Campos do Jordão 2005        29
17a. Edição Campos do Jordão 2016       25
5a. Edição Campos do Jordão 2003        24
16a. Edição Campos do Jordão 2015       23
8a. Edição Campos do Jordão 2006        22
11a. Edição Campos do Jordão 2010       21
10a. Edição Rio de Janeiro 2008         21
19a. Edição Campina Grande 2018         20
15a. Edição Campos do Jordão 2014       20
4a. Edição Caxambú 2002                 20
3a. Edição Rio de Janeiro 2001          19
13a. Edição Campos do Jordão 2012       18
2a. Edição São paulo 2000               18
14a. Edição Campos do Jordão 2013       17
12a. Edição Campos do Jordão 2011       17
1a. Edição Campinas 1999                11
Name: count, dtype: int64

## 2.2. Salvar os Artigos Coletados

In [8]:
df.to_csv(ARQUIVO_SAIDA, index=False, encoding="utf-8-sig")

In [9]:
print("=-" * 30)
print("[SUCESSO] Coleta finalizada!")
print("=-" * 30)

print(f"Total de artigos: {len(df)}")
print(f"Total de edições: {df['edicao'].nunique()}")
print(f"Arquivo: {ARQUIVO_SAIDA}")

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[SUCESSO] Coleta finalizada!
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Total de artigos: 683
Total de edições: 25
Arquivo: ..\data\raw\geoinfo_artigos_raw.csv

# 3. Análise Exploratória dos Dados

In [10]:
df_artigos = pd.read_csv(ARQUIVO_SAIDA)

In [11]:
df_artigos.describe()

               ano
count   683.000000
mean   2013.705710
std       7.882183
min    1999.000000
25%    2006.000000
50%    2015.000000
75%    2021.000000
max    2025.000000

In [12]:
df_artigos.isna().sum()

titulo           0
ano              0
autores          0
instituicoes     5
edicao           0
identificador    0
language         1
url_edicao       0
url_artigo       0
url_metadata     0
dtype: int64

In [13]:
duplicatas = df_artigos[df_artigos.duplicated("identificador", keep=False)]
print(f"Registros duplicados: {len(duplicatas)}")

Registros duplicados: 0

In [14]:
print("\nValores únicos por coluna:")
for coluna in df_artigos.columns:
    print(f"\n-=-=- {coluna} -=-=-")
    print(df_artigos[coluna].nunique(dropna=False))
    print(df_artigos[coluna].drop_duplicates().tolist()[:])

Valores únicos por coluna:

-=-=- titulo -=-=-
682

In [15]:
duplicatas_titulo = df_artigos[df_artigos.duplicated("titulo", keep=False)]
print(f"Títulos duplicados: {len(duplicatas_titulo)}")
duplicatas_titulo

Títulos duplicados: 2

,titulo,ano,autores,instituicoes,edicao,identificador,language,url_edicao,url_artigo,url_metadata
611,Image data handling in spatial databases,2003,"1 Souza, Ricardo Cartaxo Modesto De 2 Câmara, ...",1 Instituto Nacional de Pesquisas Espaciais (I...,5a. Edição Campos do Jordão 2003,83LX3pFwXQZ3V9uMbiY/MhUig,en,http://urlib.net/rep/8JMKD3MGP8W/3H5FH2B,http://mtc-m16c.sid.inpe.br/col/dpi.inpe.br/ge...,http://mtc-m16c.sid.inpe.br/dpi.inpe.br/geoinf...
613,Image data handling in spatial databases,2003,"1 Vinhas, Lúbia 2 Souza, Ricardo Cartaxo Modes...",1 Instituto Nacional de Pesquisas Espaciais (I...,5a. Edição Campos do Jordão 2003,6qtX3pFwXQZ3P8SECKy/AKNUN,pt,http://urlib.net/rep/8JMKD3MGP8W/3H5FH2B,http://mtc-m16c.sid.inpe.br/col/sid.inpe.br/je...,http://mtc-m16c.sid.inpe.br/sid.inpe.br/jefers...

In [30]:
df_artigos[df_artigos["language"].isna()]

,titulo,ano,autores,instituicoes,edicao,identificador,language,url_edicao,url_artigo,url_metadata,numero_edicao
338,Web services for big Earth observation data,2016,"1 Vinhas, Lúbia 2 Queiroz, Gilberto Ribeiro de...",1 Instituto Nacional de Pesquisas Espaciais (I...,17a. Edição Campos do Jordão 2016,8JMKD3MGP3W34P/3N2U9JL,<NA>,http://urlib.net/rep/8JMKD3MGPDW34P/42T2PKB,http://mtc-m21b.sid.inpe.br/col/sid.inpe.br/mt...,http://mtc-m21b.sid.inpe.br/sid.inpe.br/mtc-m2...,17

# 4. Pré-Processamento

## 4.1. Tratamento das Colunas

In [16]:
df_artigos["titulo"] = df_artigos["titulo"].str.strip()
df_artigos["autores"] = df_artigos["autores"].str.strip()
df_artigos["instituicoes"] = df_artigos["instituicoes"].str.strip()
df_artigos["identificador"] = df_artigos["identificador"].str.strip()
df_artigos["ano"] = pd.to_numeric(df_artigos["ano"], errors="coerce").astype("Int64")
df_artigos["edicao"] = df_artigos["edicao"].str.strip()

In [17]:
df_artigos["numero_edicao"] = (pd.to_numeric(df_artigos["edicao"].str.extract(r"(\d+)")[0], errors="coerce").astype("Int64"))

In [32]:
df_artigos.rename(columns={"language": "idioma"}, inplace=True)

## 4.2. Duplicatas

In [18]:
df_artigos = df_artigos.drop_duplicates(subset="titulo", keep="first").reset_index(drop=True)

In [19]:
duplicatas_titulo = df_artigos[df_artigos.duplicated("titulo", keep=False)]
print(f"Títulos duplicados restantes: {len(duplicatas_titulo)}")

Títulos duplicados restantes: 0

In [20]:
titulos = df_artigos["titulo"].dropna().unique()

possiveis_duplicatas = []

for i in range(len(titulos)):
    for j in range(i + 1, len(titulos)):
        similaridade = similaridade_titulos(titulos[i], titulos[j])

        if similaridade >= 0.80:
            possiveis_duplicatas.append({
                "titulo_1": titulos[i],
                "titulo_2": titulos[j],
                "similaridade": similaridade
            })

In [21]:
pd.DataFrame(possiveis_duplicatas).sort_values("similaridade", ascending=False)

,titulo_1,titulo_2,similaridade
1,Improvements to Expectation-Maximization appro...,Improvements to expectation-maximization appro...,0.995169
2,The architecture of a mobile emergency plan de...,The architecture of an emergency plan deployme...,0.931034
0,GeoSQL+: um aplicativo online de apoio ao apre...,GeoSQL: um ambiente online para aprendizado de...,0.848101

In [22]:
titulo = "Improvements to Expectation-Maximization approach for unsupervied classification of remote sensing data"

df_artigos = df_artigos[df_artigos["titulo"] != titulo].copy()

## 4.3. Preencher dados faltantes

In [23]:
df_artigos = corrigir_instituicoes_manuais(df_artigos)

In [24]:
sem_instituicao = df_artigos[df_artigos["instituicoes"].isna()]
print(f"Artigos sem instituição: {len(sem_instituicao)}")

Artigos sem instituição: 0

In [25]:
sem_instituicao

Empty DataFrame
Columns: [titulo, ano, autores, instituicoes, edicao, identificador, language, url_edicao, url_artigo, url_metadata, numero_edicao]
Index: []

In [26]:
df_artigos[df_artigos["edicao"].isna()]

Empty DataFrame
Columns: [titulo, ano, autores, instituicoes, edicao, identificador, language, url_edicao, url_artigo, url_metadata, numero_edicao]
Index: []

In [36]:
df_artigos.loc[df_artigos["identificador"] == "8JMKD3MGP3W34P/3N2U9JL", "idioma"] = "en"

In [37]:
df_artigos[df_artigos["idioma"].isna()]

Empty DataFrame
Columns: [titulo, ano, autores, instituicoes, edicao, identificador, idioma, url_edicao, url_artigo, url_metadata, numero_edicao]
Index: []

## 4.4. Padroniza e limpa dados

In [38]:
df_artigos = limpar_artigos(df_artigos)

## 4.5. Salva arquivo

In [39]:
df_artigos.info()

<class 'pandas.DataFrame'>
Index: 681 entries, 0 to 681
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titulo         681 non-null    string
 1   ano            681 non-null    Int64
 2   autores        681 non-null    string
 3   instituicoes   681 non-null    string
 4   edicao         681 non-null    string
 5   identificador  681 non-null    string
 6   idioma         681 non-null    string
 7   url_edicao     681 non-null    string
 8   url_artigo     681 non-null    string
 9   url_metadata   681 non-null    string
 10  numero_edicao  681 non-null    Int64
dtypes: Int64(2), string(9)
memory usage: 65.2 KB

In [40]:
df_artigos.to_csv(ARQUIVO_PROCESSADO, index=False, encoding="utf-8-sig")